# Generated by Django 3.2.3 on 2021-06-01 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('show_name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=100)),
                ('show_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('create_date', models.DateField(verbose_name=datetime.date.today)),
                ('file_type', models.CharField(max_length=10)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.show')),
            ],
        ),
    ]
