# Generated by Django 3.2.3 on 2021-06-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.AddField(
            model_name='show',
            name='category',
            field=models.CharField(default='Education', max_length=50),
        ),
    ]
