# Generated by Django 3.2.3 on 2021-06-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20210602_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_type',
            field=models.CharField(choices=[('MP3', 'MP3'), ('AAC', 'AAC'), ('WAV', 'WAV')], max_length=10),
        ),
    ]
