# Generated by Django 3.2.3 on 2021-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_alter_audio_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
    ]
