# Generated by Django 3.2.3 on 2021-06-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_alter_audio_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
