# Generated by Django 3.2.3 on 2021-06-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_alter_audio_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='create_date',
            new_name='post_date',
        ),
    ]
