# Generated by Django 3.2.3 on 2021-06-05 07:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0008_alter_show_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='favorite',
            field=models.ManyToManyField(related_name='show_favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
