# Generated by Django 3.2.3 on 2021-06-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_show_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='audio',
            name='file_title',
            field=models.CharField(max_length=100),
        ),
    ]
