# Generated by Django 3.2.3 on 2021-06-05 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radio', '0010_auto_20210605_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
