# Generated by Django 3.2.3 on 2021-06-06 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_alter_audio_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='favorite',
            new_name='audio_favorite',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='favorite',
            new_name='show_favorite',
        ),
    ]
