# Generated by Django 3.2.3 on 2021-06-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_auto_20210606_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_favorite',
            new_name='favorite',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='show_favorite',
            new_name='favorite',
        ),
    ]
