# Generated by Django 3.2.3 on 2021-06-13 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0015_auto_20210607_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
