# Generated by Django 3.2.3 on 2021-06-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_alter_show_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='show',
            name='post_date',
        ),
    ]
