# Generated by Django 3.2.3 on 2021-06-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0018_auto_20210615_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={},
        ),
    ]
